version: '3.9'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ./client:/app           
      - /app/node_modules       
    stdin_open: true
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true 
    env_file:
      - .env

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - '5050:5050'
    volumes:
      - ./server:/app            
      - /app/node_modules
    env_file:
      - .env